[package]
authors = ["Nelson Chen <crazysim@gmail.com>"]
name = "uds-to-web"
version = "0.1.0"

[dependencies]
futures = "0.1.15"
tokio-core = "0.1.9"
tokio-io = "0.1.3"
tokio-tungstenite = "0.3.0"
tungstenite = "0.4.0"
